// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatBeatProto.proto

package com.cs.common.model;

public final class HeartBeatProtoBuf {
  private HeartBeatProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatPongDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatPongDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 默认:"heartBeat"，详见
     * </pre>
     *
     * <code>int32 msgType = 1;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <pre>
     *当前设备imei
     * </pre>
     *
     * <code>string imei = 2;</code>
     * @return The imei.
     */
    String getImei();
    /**
     * <pre>
     *当前设备imei
     * </pre>
     *
     * <code>string imei = 2;</code>
     * @return The bytes for imei.
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <pre>
     * 设备ip
     * </pre>
     *
     * <code>string deviceIp = 3;</code>
     * @return The deviceIp.
     */
    String getDeviceIp();
    /**
     * <pre>
     * 设备ip
     * </pre>
     *
     * <code>string deviceIp = 3;</code>
     * @return The bytes for deviceIp.
     */
    com.google.protobuf.ByteString
        getDeviceIpBytes();

    /**
     * <pre>
     *终端屏幕分辨率
     * </pre>
     *
     * <code>string deviceResolution = 4;</code>
     * @return The deviceResolution.
     */
    String getDeviceResolution();
    /**
     * <pre>
     *终端屏幕分辨率
     * </pre>
     *
     * <code>string deviceResolution = 4;</code>
     * @return The bytes for deviceResolution.
     */
    com.google.protobuf.ByteString
        getDeviceResolutionBytes();

    /**
     * <pre>
     *摄像头运行状态 0：异常 1：正常'
     * </pre>
     *
     * <code>int32 cameraWorkStatus = 5;</code>
     * @return The cameraWorkStatus.
     */
    int getCameraWorkStatus();

    /**
     * <pre>
     * 终端音量
     * </pre>
     *
     * <code>int32 deviceVolume = 6;</code>
     * @return The deviceVolume.
     */
    int getDeviceVolume();

    /**
     * <pre>
     *屏幕亮度 默认20
     * </pre>
     *
     * <code>string screenBrightness = 7;</code>
     * @return The screenBrightness.
     */
    String getScreenBrightness();
    /**
     * <pre>
     *屏幕亮度 默认20
     * </pre>
     *
     * <code>string screenBrightness = 7;</code>
     * @return The bytes for screenBrightness.
     */
    com.google.protobuf.ByteString
        getScreenBrightnessBytes();

    /**
     * <pre>
     *是否背光（0：否 1：是）
     * </pre>
     *
     * <code>int32 isBlacklight = 8;</code>
     * @return The isBlacklight.
     */
    int getIsBlacklight();

    /**
     * <pre>
     *是否开机自启（0：否 1：是）
     * </pre>
     *
     * <code>int32 isRootStart = 9;</code>
     * @return The isRootStart.
     */
    int getIsRootStart();

    /**
     * <pre>
     *是否开启进程守护（0 否 1：是）
     * </pre>
     *
     * <code>int32 isGuard = 10;</code>
     * @return The isGuard.
     */
    int getIsGuard();

    /**
     * <pre>
     *是否显示状态栏（0：否 1：是）
     * </pre>
     *
     * <code>int32 isStatus = 11;</code>
     * @return The isStatus.
     */
    int getIsStatus();
  }
  /**
   * <pre>
   * c-&gt;s (客户端Client发送给服务端Server) 相当于回复 pong
   * </pre>
   *
   * Protobuf type {@code HeartBeatPongDTO}
   */
  public static final class HeartBeatPongDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatPongDTO)
      HeartBeatPongDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatPongDTO.newBuilder() to construct.
    private HeartBeatPongDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatPongDTO() {
      imei_ = "";
      deviceIp_ = "";
      deviceResolution_ = "";
      screenBrightness_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeatPongDTO();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatPongDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgType_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              imei_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              deviceIp_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              deviceResolution_ = s;
              break;
            }
            case 40: {

              cameraWorkStatus_ = input.readInt32();
              break;
            }
            case 48: {

              deviceVolume_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              screenBrightness_ = s;
              break;
            }
            case 64: {

              isBlacklight_ = input.readInt32();
              break;
            }
            case 72: {

              isRootStart_ = input.readInt32();
              break;
            }
            case 80: {

              isGuard_ = input.readInt32();
              break;
            }
            case 88: {

              isStatus_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartBeatProtoBuf.internal_static_HeartBeatPongDTO_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartBeatProtoBuf.internal_static_HeartBeatPongDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatPongDTO.class, Builder.class);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <pre>
     * 默认:"heartBeat"，详见
     * </pre>
     *
     * <code>int32 msgType = 1;</code>
     * @return The msgType.
     */
    @Override
    public int getMsgType() {
      return msgType_;
    }

    public static final int IMEI_FIELD_NUMBER = 2;
    private volatile Object imei_;
    /**
     * <pre>
     *当前设备imei
     * </pre>
     *
     * <code>string imei = 2;</code>
     * @return The imei.
     */
    @Override
    public String getImei() {
      Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前设备imei
     * </pre>
     *
     * <code>string imei = 2;</code>
     * @return The bytes for imei.
     */
    @Override
    public com.google.protobuf.ByteString
        getImeiBytes() {
      Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEIP_FIELD_NUMBER = 3;
    private volatile Object deviceIp_;
    /**
     * <pre>
     * 设备ip
     * </pre>
     *
     * <code>string deviceIp = 3;</code>
     * @return The deviceIp.
     */
    @Override
    public String getDeviceIp() {
      Object ref = deviceIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备ip
     * </pre>
     *
     * <code>string deviceIp = 3;</code>
     * @return The bytes for deviceIp.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      Object ref = deviceIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICERESOLUTION_FIELD_NUMBER = 4;
    private volatile Object deviceResolution_;
    /**
     * <pre>
     *终端屏幕分辨率
     * </pre>
     *
     * <code>string deviceResolution = 4;</code>
     * @return The deviceResolution.
     */
    @Override
    public String getDeviceResolution() {
      Object ref = deviceResolution_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceResolution_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *终端屏幕分辨率
     * </pre>
     *
     * <code>string deviceResolution = 4;</code>
     * @return The bytes for deviceResolution.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceResolutionBytes() {
      Object ref = deviceResolution_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceResolution_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAMERAWORKSTATUS_FIELD_NUMBER = 5;
    private int cameraWorkStatus_;
    /**
     * <pre>
     *摄像头运行状态 0：异常 1：正常'
     * </pre>
     *
     * <code>int32 cameraWorkStatus = 5;</code>
     * @return The cameraWorkStatus.
     */
    @Override
    public int getCameraWorkStatus() {
      return cameraWorkStatus_;
    }

    public static final int DEVICEVOLUME_FIELD_NUMBER = 6;
    private int deviceVolume_;
    /**
     * <pre>
     * 终端音量
     * </pre>
     *
     * <code>int32 deviceVolume = 6;</code>
     * @return The deviceVolume.
     */
    @Override
    public int getDeviceVolume() {
      return deviceVolume_;
    }

    public static final int SCREENBRIGHTNESS_FIELD_NUMBER = 7;
    private volatile Object screenBrightness_;
    /**
     * <pre>
     *屏幕亮度 默认20
     * </pre>
     *
     * <code>string screenBrightness = 7;</code>
     * @return The screenBrightness.
     */
    @Override
    public String getScreenBrightness() {
      Object ref = screenBrightness_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        screenBrightness_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *屏幕亮度 默认20
     * </pre>
     *
     * <code>string screenBrightness = 7;</code>
     * @return The bytes for screenBrightness.
     */
    @Override
    public com.google.protobuf.ByteString
        getScreenBrightnessBytes() {
      Object ref = screenBrightness_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        screenBrightness_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISBLACKLIGHT_FIELD_NUMBER = 8;
    private int isBlacklight_;
    /**
     * <pre>
     *是否背光（0：否 1：是）
     * </pre>
     *
     * <code>int32 isBlacklight = 8;</code>
     * @return The isBlacklight.
     */
    @Override
    public int getIsBlacklight() {
      return isBlacklight_;
    }

    public static final int ISROOTSTART_FIELD_NUMBER = 9;
    private int isRootStart_;
    /**
     * <pre>
     *是否开机自启（0：否 1：是）
     * </pre>
     *
     * <code>int32 isRootStart = 9;</code>
     * @return The isRootStart.
     */
    @Override
    public int getIsRootStart() {
      return isRootStart_;
    }

    public static final int ISGUARD_FIELD_NUMBER = 10;
    private int isGuard_;
    /**
     * <pre>
     *是否开启进程守护（0 否 1：是）
     * </pre>
     *
     * <code>int32 isGuard = 10;</code>
     * @return The isGuard.
     */
    @Override
    public int getIsGuard() {
      return isGuard_;
    }

    public static final int ISSTATUS_FIELD_NUMBER = 11;
    private int isStatus_;
    /**
     * <pre>
     *是否显示状态栏（0：否 1：是）
     * </pre>
     *
     * <code>int32 isStatus = 11;</code>
     * @return The isStatus.
     */
    @Override
    public int getIsStatus() {
      return isStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != 0) {
        output.writeInt32(1, msgType_);
      }
      if (!getImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imei_);
      }
      if (!getDeviceIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceIp_);
      }
      if (!getDeviceResolutionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceResolution_);
      }
      if (cameraWorkStatus_ != 0) {
        output.writeInt32(5, cameraWorkStatus_);
      }
      if (deviceVolume_ != 0) {
        output.writeInt32(6, deviceVolume_);
      }
      if (!getScreenBrightnessBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, screenBrightness_);
      }
      if (isBlacklight_ != 0) {
        output.writeInt32(8, isBlacklight_);
      }
      if (isRootStart_ != 0) {
        output.writeInt32(9, isRootStart_);
      }
      if (isGuard_ != 0) {
        output.writeInt32(10, isGuard_);
      }
      if (isStatus_ != 0) {
        output.writeInt32(11, isStatus_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (!getImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imei_);
      }
      if (!getDeviceIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceIp_);
      }
      if (!getDeviceResolutionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceResolution_);
      }
      if (cameraWorkStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cameraWorkStatus_);
      }
      if (deviceVolume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, deviceVolume_);
      }
      if (!getScreenBrightnessBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, screenBrightness_);
      }
      if (isBlacklight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, isBlacklight_);
      }
      if (isRootStart_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, isRootStart_);
      }
      if (isGuard_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, isGuard_);
      }
      if (isStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, isStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeartBeatPongDTO)) {
        return super.equals(obj);
      }
      HeartBeatPongDTO other = (HeartBeatPongDTO) obj;

      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getImei()
          .equals(other.getImei())) return false;
      if (!getDeviceIp()
          .equals(other.getDeviceIp())) return false;
      if (!getDeviceResolution()
          .equals(other.getDeviceResolution())) return false;
      if (getCameraWorkStatus()
          != other.getCameraWorkStatus()) return false;
      if (getDeviceVolume()
          != other.getDeviceVolume()) return false;
      if (!getScreenBrightness()
          .equals(other.getScreenBrightness())) return false;
      if (getIsBlacklight()
          != other.getIsBlacklight()) return false;
      if (getIsRootStart()
          != other.getIsRootStart()) return false;
      if (getIsGuard()
          != other.getIsGuard()) return false;
      if (getIsStatus()
          != other.getIsStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getImei().hashCode();
      hash = (37 * hash) + DEVICEIP_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceIp().hashCode();
      hash = (37 * hash) + DEVICERESOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceResolution().hashCode();
      hash = (37 * hash) + CAMERAWORKSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getCameraWorkStatus();
      hash = (37 * hash) + DEVICEVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceVolume();
      hash = (37 * hash) + SCREENBRIGHTNESS_FIELD_NUMBER;
      hash = (53 * hash) + getScreenBrightness().hashCode();
      hash = (37 * hash) + ISBLACKLIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getIsBlacklight();
      hash = (37 * hash) + ISROOTSTART_FIELD_NUMBER;
      hash = (53 * hash) + getIsRootStart();
      hash = (37 * hash) + ISGUARD_FIELD_NUMBER;
      hash = (53 * hash) + getIsGuard();
      hash = (37 * hash) + ISSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getIsStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeartBeatPongDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPongDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPongDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPongDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPongDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPongDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPongDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatPongDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatPongDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeartBeatPongDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatPongDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatPongDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeartBeatPongDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * c-&gt;s (客户端Client发送给服务端Server) 相当于回复 pong
     * </pre>
     *
     * Protobuf type {@code HeartBeatPongDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatPongDTO)
        HeartBeatPongDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPongDTO_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPongDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatPongDTO.class, Builder.class);
      }

      // Construct using com.cs.common.model.HeartBeatProtoBuf.HeartBeatPongDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        imei_ = "";

        deviceIp_ = "";

        deviceResolution_ = "";

        cameraWorkStatus_ = 0;

        deviceVolume_ = 0;

        screenBrightness_ = "";

        isBlacklight_ = 0;

        isRootStart_ = 0;

        isGuard_ = 0;

        isStatus_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPongDTO_descriptor;
      }

      @Override
      public HeartBeatPongDTO getDefaultInstanceForType() {
        return HeartBeatPongDTO.getDefaultInstance();
      }

      @Override
      public HeartBeatPongDTO build() {
        HeartBeatPongDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HeartBeatPongDTO buildPartial() {
        HeartBeatPongDTO result = new HeartBeatPongDTO(this);
        result.msgType_ = msgType_;
        result.imei_ = imei_;
        result.deviceIp_ = deviceIp_;
        result.deviceResolution_ = deviceResolution_;
        result.cameraWorkStatus_ = cameraWorkStatus_;
        result.deviceVolume_ = deviceVolume_;
        result.screenBrightness_ = screenBrightness_;
        result.isBlacklight_ = isBlacklight_;
        result.isRootStart_ = isRootStart_;
        result.isGuard_ = isGuard_;
        result.isStatus_ = isStatus_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatPongDTO) {
          return mergeFrom((HeartBeatPongDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatPongDTO other) {
        if (other == HeartBeatPongDTO.getDefaultInstance()) return this;
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getImei().isEmpty()) {
          imei_ = other.imei_;
          onChanged();
        }
        if (!other.getDeviceIp().isEmpty()) {
          deviceIp_ = other.deviceIp_;
          onChanged();
        }
        if (!other.getDeviceResolution().isEmpty()) {
          deviceResolution_ = other.deviceResolution_;
          onChanged();
        }
        if (other.getCameraWorkStatus() != 0) {
          setCameraWorkStatus(other.getCameraWorkStatus());
        }
        if (other.getDeviceVolume() != 0) {
          setDeviceVolume(other.getDeviceVolume());
        }
        if (!other.getScreenBrightness().isEmpty()) {
          screenBrightness_ = other.screenBrightness_;
          onChanged();
        }
        if (other.getIsBlacklight() != 0) {
          setIsBlacklight(other.getIsBlacklight());
        }
        if (other.getIsRootStart() != 0) {
          setIsRootStart(other.getIsRootStart());
        }
        if (other.getIsGuard() != 0) {
          setIsGuard(other.getIsGuard());
        }
        if (other.getIsStatus() != 0) {
          setIsStatus(other.getIsStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatPongDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatPongDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       * 默认:"heartBeat"，详见
       * </pre>
       *
       * <code>int32 msgType = 1;</code>
       * @return The msgType.
       */
      @Override
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * 默认:"heartBeat"，详见
       * </pre>
       *
       * <code>int32 msgType = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 默认:"heartBeat"，详见
       * </pre>
       *
       * <code>int32 msgType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object imei_ = "";
      /**
       * <pre>
       *当前设备imei
       * </pre>
       *
       * <code>string imei = 2;</code>
       * @return The imei.
       */
      public String getImei() {
        Object ref = imei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *当前设备imei
       * </pre>
       *
       * <code>string imei = 2;</code>
       * @return The bytes for imei.
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前设备imei
       * </pre>
       *
       * <code>string imei = 2;</code>
       * @param value The imei to set.
       * @return This builder for chaining.
       */
      public Builder setImei(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前设备imei
       * </pre>
       *
       * <code>string imei = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImei() {
        
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前设备imei
       * </pre>
       *
       * <code>string imei = 2;</code>
       * @param value The bytes for imei to set.
       * @return This builder for chaining.
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imei_ = value;
        onChanged();
        return this;
      }

      private Object deviceIp_ = "";
      /**
       * <pre>
       * 设备ip
       * </pre>
       *
       * <code>string deviceIp = 3;</code>
       * @return The deviceIp.
       */
      public String getDeviceIp() {
        Object ref = deviceIp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 设备ip
       * </pre>
       *
       * <code>string deviceIp = 3;</code>
       * @return The bytes for deviceIp.
       */
      public com.google.protobuf.ByteString
          getDeviceIpBytes() {
        Object ref = deviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备ip
       * </pre>
       *
       * <code>string deviceIp = 3;</code>
       * @param value The deviceIp to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备ip
       * </pre>
       *
       * <code>string deviceIp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceIp() {
        
        deviceIp_ = getDefaultInstance().getDeviceIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备ip
       * </pre>
       *
       * <code>string deviceIp = 3;</code>
       * @param value The bytes for deviceIp to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceIp_ = value;
        onChanged();
        return this;
      }

      private Object deviceResolution_ = "";
      /**
       * <pre>
       *终端屏幕分辨率
       * </pre>
       *
       * <code>string deviceResolution = 4;</code>
       * @return The deviceResolution.
       */
      public String getDeviceResolution() {
        Object ref = deviceResolution_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceResolution_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *终端屏幕分辨率
       * </pre>
       *
       * <code>string deviceResolution = 4;</code>
       * @return The bytes for deviceResolution.
       */
      public com.google.protobuf.ByteString
          getDeviceResolutionBytes() {
        Object ref = deviceResolution_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceResolution_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *终端屏幕分辨率
       * </pre>
       *
       * <code>string deviceResolution = 4;</code>
       * @param value The deviceResolution to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceResolution(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceResolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *终端屏幕分辨率
       * </pre>
       *
       * <code>string deviceResolution = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceResolution() {
        
        deviceResolution_ = getDefaultInstance().getDeviceResolution();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *终端屏幕分辨率
       * </pre>
       *
       * <code>string deviceResolution = 4;</code>
       * @param value The bytes for deviceResolution to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceResolutionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceResolution_ = value;
        onChanged();
        return this;
      }

      private int cameraWorkStatus_ ;
      /**
       * <pre>
       *摄像头运行状态 0：异常 1：正常'
       * </pre>
       *
       * <code>int32 cameraWorkStatus = 5;</code>
       * @return The cameraWorkStatus.
       */
      @Override
      public int getCameraWorkStatus() {
        return cameraWorkStatus_;
      }
      /**
       * <pre>
       *摄像头运行状态 0：异常 1：正常'
       * </pre>
       *
       * <code>int32 cameraWorkStatus = 5;</code>
       * @param value The cameraWorkStatus to set.
       * @return This builder for chaining.
       */
      public Builder setCameraWorkStatus(int value) {
        
        cameraWorkStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *摄像头运行状态 0：异常 1：正常'
       * </pre>
       *
       * <code>int32 cameraWorkStatus = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraWorkStatus() {
        
        cameraWorkStatus_ = 0;
        onChanged();
        return this;
      }

      private int deviceVolume_ ;
      /**
       * <pre>
       * 终端音量
       * </pre>
       *
       * <code>int32 deviceVolume = 6;</code>
       * @return The deviceVolume.
       */
      @Override
      public int getDeviceVolume() {
        return deviceVolume_;
      }
      /**
       * <pre>
       * 终端音量
       * </pre>
       *
       * <code>int32 deviceVolume = 6;</code>
       * @param value The deviceVolume to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceVolume(int value) {
        
        deviceVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端音量
       * </pre>
       *
       * <code>int32 deviceVolume = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceVolume() {
        
        deviceVolume_ = 0;
        onChanged();
        return this;
      }

      private Object screenBrightness_ = "";
      /**
       * <pre>
       *屏幕亮度 默认20
       * </pre>
       *
       * <code>string screenBrightness = 7;</code>
       * @return The screenBrightness.
       */
      public String getScreenBrightness() {
        Object ref = screenBrightness_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          screenBrightness_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *屏幕亮度 默认20
       * </pre>
       *
       * <code>string screenBrightness = 7;</code>
       * @return The bytes for screenBrightness.
       */
      public com.google.protobuf.ByteString
          getScreenBrightnessBytes() {
        Object ref = screenBrightness_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          screenBrightness_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *屏幕亮度 默认20
       * </pre>
       *
       * <code>string screenBrightness = 7;</code>
       * @param value The screenBrightness to set.
       * @return This builder for chaining.
       */
      public Builder setScreenBrightness(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        screenBrightness_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *屏幕亮度 默认20
       * </pre>
       *
       * <code>string screenBrightness = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearScreenBrightness() {
        
        screenBrightness_ = getDefaultInstance().getScreenBrightness();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *屏幕亮度 默认20
       * </pre>
       *
       * <code>string screenBrightness = 7;</code>
       * @param value The bytes for screenBrightness to set.
       * @return This builder for chaining.
       */
      public Builder setScreenBrightnessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        screenBrightness_ = value;
        onChanged();
        return this;
      }

      private int isBlacklight_ ;
      /**
       * <pre>
       *是否背光（0：否 1：是）
       * </pre>
       *
       * <code>int32 isBlacklight = 8;</code>
       * @return The isBlacklight.
       */
      @Override
      public int getIsBlacklight() {
        return isBlacklight_;
      }
      /**
       * <pre>
       *是否背光（0：否 1：是）
       * </pre>
       *
       * <code>int32 isBlacklight = 8;</code>
       * @param value The isBlacklight to set.
       * @return This builder for chaining.
       */
      public Builder setIsBlacklight(int value) {
        
        isBlacklight_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否背光（0：否 1：是）
       * </pre>
       *
       * <code>int32 isBlacklight = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsBlacklight() {
        
        isBlacklight_ = 0;
        onChanged();
        return this;
      }

      private int isRootStart_ ;
      /**
       * <pre>
       *是否开机自启（0：否 1：是）
       * </pre>
       *
       * <code>int32 isRootStart = 9;</code>
       * @return The isRootStart.
       */
      @Override
      public int getIsRootStart() {
        return isRootStart_;
      }
      /**
       * <pre>
       *是否开机自启（0：否 1：是）
       * </pre>
       *
       * <code>int32 isRootStart = 9;</code>
       * @param value The isRootStart to set.
       * @return This builder for chaining.
       */
      public Builder setIsRootStart(int value) {
        
        isRootStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否开机自启（0：否 1：是）
       * </pre>
       *
       * <code>int32 isRootStart = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsRootStart() {
        
        isRootStart_ = 0;
        onChanged();
        return this;
      }

      private int isGuard_ ;
      /**
       * <pre>
       *是否开启进程守护（0 否 1：是）
       * </pre>
       *
       * <code>int32 isGuard = 10;</code>
       * @return The isGuard.
       */
      @Override
      public int getIsGuard() {
        return isGuard_;
      }
      /**
       * <pre>
       *是否开启进程守护（0 否 1：是）
       * </pre>
       *
       * <code>int32 isGuard = 10;</code>
       * @param value The isGuard to set.
       * @return This builder for chaining.
       */
      public Builder setIsGuard(int value) {
        
        isGuard_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否开启进程守护（0 否 1：是）
       * </pre>
       *
       * <code>int32 isGuard = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsGuard() {
        
        isGuard_ = 0;
        onChanged();
        return this;
      }

      private int isStatus_ ;
      /**
       * <pre>
       *是否显示状态栏（0：否 1：是）
       * </pre>
       *
       * <code>int32 isStatus = 11;</code>
       * @return The isStatus.
       */
      @Override
      public int getIsStatus() {
        return isStatus_;
      }
      /**
       * <pre>
       *是否显示状态栏（0：否 1：是）
       * </pre>
       *
       * <code>int32 isStatus = 11;</code>
       * @param value The isStatus to set.
       * @return This builder for chaining.
       */
      public Builder setIsStatus(int value) {
        
        isStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否显示状态栏（0：否 1：是）
       * </pre>
       *
       * <code>int32 isStatus = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsStatus() {
        
        isStatus_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatPongDTO)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatPongDTO)
    private static final HeartBeatPongDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeartBeatPongDTO();
    }

    public static HeartBeatPongDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatPongDTO>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatPongDTO>() {
      @Override
      public HeartBeatPongDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatPongDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatPongDTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HeartBeatPongDTO> getParserForType() {
      return PARSER;
    }

    @Override
    public HeartBeatPongDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatPingDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatPingDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     *content,消息的内容,比如说:"are you alive?"
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     *content,消息的内容,比如说:"are you alive?"
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * s-&gt;c (服务端Server发送给客户端Client) 相当于ping
   * </pre>
   *
   * Protobuf type {@code HeartBeatPingDTO}
   */
  public static final class HeartBeatPingDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatPingDTO)
      HeartBeatPingDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatPingDTO.newBuilder() to construct.
    private HeartBeatPingDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatPingDTO() {
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeatPingDTO();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatPingDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartBeatProtoBuf.internal_static_HeartBeatPingDTO_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartBeatProtoBuf.internal_static_HeartBeatPingDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatPingDTO.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile Object content_;
    /**
     * <pre>
     *content,消息的内容,比如说:"are you alive?"
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *content,消息的内容,比如说:"are you alive?"
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeartBeatPingDTO)) {
        return super.equals(obj);
      }
      HeartBeatPingDTO other = (HeartBeatPingDTO) obj;

      if (getId()
          != other.getId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeartBeatPingDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPingDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPingDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPingDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPingDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatPingDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatPingDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatPingDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatPingDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeartBeatPingDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeartBeatPingDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeartBeatPingDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeartBeatPingDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * s-&gt;c (服务端Server发送给客户端Client) 相当于ping
     * </pre>
     *
     * Protobuf type {@code HeartBeatPingDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatPingDTO)
        HeartBeatPingDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPingDTO_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPingDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatPingDTO.class, Builder.class);
      }

      // Construct using com.cs.common.model.HeartBeatProtoBuf.HeartBeatPingDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        content_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartBeatProtoBuf.internal_static_HeartBeatPingDTO_descriptor;
      }

      @Override
      public HeartBeatPingDTO getDefaultInstanceForType() {
        return HeartBeatPingDTO.getDefaultInstance();
      }

      @Override
      public HeartBeatPingDTO build() {
        HeartBeatPingDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HeartBeatPingDTO buildPartial() {
        HeartBeatPingDTO result = new HeartBeatPingDTO(this);
        result.id_ = id_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatPingDTO) {
          return mergeFrom((HeartBeatPingDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatPingDTO other) {
        if (other == HeartBeatPingDTO.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatPingDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatPingDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       *content,消息的内容,比如说:"are you alive?"
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *content,消息的内容,比如说:"are you alive?"
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *content,消息的内容,比如说:"are you alive?"
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *content,消息的内容,比如说:"are you alive?"
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *content,消息的内容,比如说:"are you alive?"
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatPingDTO)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatPingDTO)
    private static final HeartBeatPingDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeartBeatPingDTO();
    }

    public static HeartBeatPingDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatPingDTO>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatPingDTO>() {
      @Override
      public HeartBeatPingDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatPingDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatPingDTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HeartBeatPingDTO> getParserForType() {
      return PARSER;
    }

    @Override
    public HeartBeatPingDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatPongDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatPongDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatPingDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatPingDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023HeatBeatProto.proto\"\365\001\n\020HeartBeatPongD" +
      "TO\022\017\n\007msgType\030\001 \001(\005\022\014\n\004imei\030\002 \001(\t\022\020\n\010dev" +
      "iceIp\030\003 \001(\t\022\030\n\020deviceResolution\030\004 \001(\t\022\030\n" +
      "\020cameraWorkStatus\030\005 \001(\005\022\024\n\014deviceVolume\030" +
      "\006 \001(\005\022\030\n\020screenBrightness\030\007 \001(\t\022\024\n\014isBla" +
      "cklight\030\010 \001(\005\022\023\n\013isRootStart\030\t \001(\005\022\017\n\007is" +
      "Guard\030\n \001(\005\022\020\n\010isStatus\030\013 \001(\005\"/\n\020HeartBe" +
      "atPingDTO\022\n\n\002id\030\001 \001(\005\022\017\n\007content\030\002 \001(\tB(" +
      "\n\023com.cs.common.modelB\021HeartBeatProtoBuf" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HeartBeatPongDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeatPongDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatPongDTO_descriptor,
        new String[] { "MsgType", "Imei", "DeviceIp", "DeviceResolution", "CameraWorkStatus", "DeviceVolume", "ScreenBrightness", "IsBlacklight", "IsRootStart", "IsGuard", "IsStatus", });
    internal_static_HeartBeatPingDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatPingDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatPingDTO_descriptor,
        new String[] { "Id", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
